#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.DropBoxChooser.Example.Resource", IsApplication=true)]

namespace Xamarin.DropBoxChooser.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int action_settings = 2131230732;
			
			// aapt resource value: 0x7f080004
			public const int chooser_button = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int filename = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int icon = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int link_type = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int link_type_content = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int link_type_direct = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int link_type_preview = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int size = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int thumb200 = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int thumb64 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int thumb640 = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int uri = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int action_settings = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int hello_world = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
